### ISSUE TITLE
test_function "_g_0" has no attribute "_imp_"

### ISSUE THREAD

**Issue by albflo** [albflo/pyinduct#1]
When the higher derivatives get converted in the `sympy_simulation_x1x2` branch, a error occurs when the `_test_function_letter` in `str(expr) `([sym_simulation.py](https://github.com/albflo/pyinduct/blob/sympy_simulation_x1x2/pyinduct/sym_simulation.py) at line 1076) calls the function `expr.func._imp_.derive(order)`. The same line gets executed when a `_function_letter` is in `str(expr)`, but the `_function_letter` has the wanted `_imp_` method.

```
Traceback (most recent call last):
  File "path/pyinduct/pyinduct/examples/symbolic_heavy_chain.py", line 323, in <module>
    results = ss.simulate_system(weak_form, rep_dict, input_map, ics, temp_dom, spat_dom)
  File "path/pyinduct/pyinduct/sym_simulation.py", line 905, in simulate_system
    ss_sys = create_first_order_system(rep_eqs, input_map)
  File "path/pyinduct/pyinduct/sym_simulation.py", line 812, in create_first_order_system
    new_forms, targets = _convert_derivatives(new_forms)
  File "path/pyinduct/pyinduct/sym_simulation.py", line 981, in _convert_derivatives
    new_forms, der)
  File "path/pyinduct/pyinduct/sym_simulation.py", line 1078, in _convert_higher_derivative
    callback = expr.func._imp_.derive(order)
AttributeError: type object '_g_0' has no attribute '_imp_'
```

**Comment by albflo** [comment]
in the example `symbolic_transport_system.py` we have also a diff of a testfunction and there it gets replaced at the `substitute_approximations()` (line:902 in `sym_simulation.py') with the command `_expand_kth_terms()` (line:697 in `sym_simulation.py'). After that the derivative of '"_g_0"' is replaced.

**Comment by albflo** [comment]
issue closed, because development of sympy_simulation branches was stopped
